services:

  mautic:
    container_name: mautic
    image: druidfi/mautic:5.0.2
    restart: unless-stopped
    env_file:
      - path: ./.env
        required: true
    volumes:
      - config:/app/config
      - media_files:/app/media/files
      - media_images:/app/media/images
      - var:/app/var
    labels:
      traefik.enable: true
      traefik.http.routers.mautic.entrypoints: https
      traefik.http.routers.mautic.rule: Host(`$MAUTIC_DOMAIN`)
      traefik.http.routers.mautic.tls: true
      traefik.http.services.mautic.loadbalancer.server.port: 8080
      traefik.docker.network: traefik-network
    networks:
      - default
      - traefik-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    container_name: db
    image: mariadb:10.11
    volumes:
      - db:/var/lib/mysql:Z
    environment:
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWD
      MYSQL_ROOT_PASSWORD: nallikuumat

networks:
  traefik-network:
    external: true

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: ./db
      o: bind
  config:
    driver: local
    driver_opts:
      type: none
      device: ./config
      o: bind
  media_files:
    driver: local
    driver_opts:
      type: none
      device: ./media/files
      o: bind
  media_images:
    driver: local
    driver_opts:
      type: none
      device: ./media/images
      o: bind
  var:
    driver: local
    driver_opts:
      type: none
      device: ./var
      o: bind
