#syntax=docker/dockerfile:1

#
# Base Mautic image v7
#
FROM mautic/mautic:7.0.0-apache AS mautic_local

RUN apt-get update && apt-get install -y libavif15 libxpm4 libwebp7 && rm -rf /var/lib/apt/lists/*

COPY files/000-default.conf /etc/apache2/sites-available/000-default.conf

COPY --chown=www-data:www-data files/shared/dxp/favicon.ico /var/www/html/docroot/app/assets/images/favicon.ico
COPY --chown=www-data:www-data files/shared/logo* /var/www/html/docroot/app/assets/images/

COPY --chown=www-data:www-data files/7/plugins/DruidXPBundle /var/www/html/docroot/plugins/DruidXPBundle
RUN test -f /var/www/html/docroot/plugins/DruidXPBundle/DruidXPBundle.php
#RUN ls -lah /var/www/html/docroot/plugins/DruidXPBundle/ && exit 1

RUN chown -R www-data:www-data /var/www/html/var
