#!/bin/sh
set -e

echo "Start up PHP-FPM..."
php-fpm -F -R &

echo "Set permissions..."
chown www-data:www-data /app/config/local.php
chown -R www-data:www-data /app/media /app/translations /app/var

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php-fpm "$@"
fi

exec "$@"
