server {
  listen [::]:8080 default_server;
  listen 8080 default_server;
  server_name _;
  client_max_body_size 512M;

  root /app;
  index index.php;

  #proxy_set_header X-Forwarded-Proto https;
  #proxy_set_header X-Forwarded-Scheme https;

  # autocomplete URLs are forced to go to index.php
  #rewrite ^/index.php / last;
  rewrite ^/index.php/(.*) /$1  permanent;

  # The 'default' location.
  location / {

    #location ~ ^/installer$ {
    #  try_files /installer @rewrite;
    #}

    # Disallow access to any dot files, but send the request to Mautic
    location ~* /\. {
      try_files /dev/null @rewrite;
    }

    # Direct Access to .php files is not allowed and is sent to Mautic instead
    location ~* ^.+\.php$ {
      try_files /dev/null @rewrite;
    }

    # Try to find a file with given URL, if not pass to Mautic
    try_files $uri @rewrite;
  }

  location @rewrite {
    include        /etc/nginx/fastcgi.conf;
    fastcgi_param  SCRIPT_NAME        /index.php;
    fastcgi_param  SCRIPT_FILENAME    $realpath_root/index.php;
    fastcgi_pass   127.0.0.1:9000;
  }

  # Disallow access to vendor directory.
  location ^~ /vendor/ {
    deny all;
    access_log off;
    log_not_found off;
  }

  # Support for favicon. Return an 1x1 transparent GIF if it doesn't
  # exist.
  location = /favicon.ico {
    expires 30d;
    try_files /favicon.ico @empty;
  }

  # Return an in memory 1x1 transparent GIF.
  location @empty {
    expires 30d;
    empty_gif;
  }

}
